---
version: "3.3"

services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Madrid
    volumes:
      - /patch/to/data/dokuwiki/appdata/config:/config
    networks:
      - proxy
    restart: always
    labels:
      # dokuwiki
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.dokuwiki.entrypoints=websecure"
      - "traefik.http.routers.dokuwiki.tls=true"
      - "traefik.http.routers.dokuwiki.tls.certresolver=lets-encrypt"
      - "traefik.http.services.dokuwiki.loadbalancer.server.port=80"
      - "traefik.http.middlewares.dokuwiki.headers.sslredirect=true"

volumes:
  dokuwiki:
    driver: local
    
networks:
  proxy:
    external: true
